apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tms.fullname" . }}-migrate-{{ now | unixEpoch }}
  labels:
    {{- include "tms.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: {{ include "tms.fullname" . }}-env
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "tms.fullname" . }}
                  key: SECRET_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "tms.fullname" . }}
                  key: DATABASE_URL
            - name: DATABASE_SYNC_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "tms.fullname" . }}
                  key: DATABASE_SYNC_URL
