apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tms.fullname" . }}
  labels:
    {{- include "tms.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.env.SECRET_KEY | default (randAlphaNum 32) | quote }}
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  DATABASE_SYNC_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  REDIS_URL: "redis://{{ .Release.Name }}-redis-master:6379/0"
  SMTP_PASSWORD: {{ .Values.env.SMTP_PASSWORD | default "" | quote }}
  SENTRY_DSN: {{ .Values.env.SENTRY_DSN | default "" | quote }}
  PG_USER: {{ .Values.postgresql.auth.username | quote }}
  PG_DATABASE: {{ .Values.postgresql.auth.database | quote }}
  PG_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
